### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by dmadrigalejos** [asalvador/gourl#3]
Url: http://ycpi-mail-rest-core4.msg.yahoo.com/v1/message/yahoo/carolynnbfields3704

Expected domain : yahoo.com
Actual domain      : yah.com

Suggestion: Use "strings.TrimSuffix" instead of "strings.TrimRight".

**Comment by asalvador** [comment]
Do you want to create a pull request for this? Just wondering. :)

**Comment by asalvador** [comment]
URL:  http://ycpi-mail-rest-core4.msg.yahoo.com/v1/message/yahoo/carolynnbfields3704
Normalized URL:  http://ycpi-mail-rest-core4.msg.yahoo.com/v1/message/yahoo/carolynnbfields3704
Scheme:  http
User:  
Password:  
Subdomain:  ycpi-mail-rest-core4.msg
Domain:  yahoo.com
Hostname:  ycpi-mail-rest-core4.msg.yahoo.com
Port:  
Path:  /v1/message/yahoo/carolynnbfields3704
Query:  
Fragment:
